### ISSUE TITLE
Incorrect NumberOfEntries in .pls playlist

### ISSUE THREAD

**Issue by pixelscoot** [Poniverse/Ponyville-Live#1]
https://github.com/Poniverse/Ponyville-Live/blob/31563f3144dc87a5459319ee493f2c2b998955aa/app/modules/frontend/controllers/StationController.php#L205
Because each station can have multiple streams, the count is incorrect here. You would need to use $i after you iterated through the stations to set NumberOfEntries properly. I don't know php so can't fork and fix myself, but should be relatively easy.

Maybe some players don't care, but foobar2000 does. It only adds 18 streams instead of expected 49. The m3u list does not have this problem and works exactly as expected.

Thanks for existing btw, after Everfree Radio died the second time it was nice to find many streams in one convenient location.

**Comment by EventideGlow** [comment]
Hey @pixelscoot - I'll take a look at fixing this in the very near future.

Thanks for such a detailed bug report and you're welcome! PVL's not going anywhere. :smiley:

**Comment by EventideGlow** [comment]
@pixelscoot This is now fixed! :horse:
