### ISSUE TITLE
Promotions on Homepage are stuck at January 2018

### ISSUE THREAD

**Issue by Vaalyn** [Poniverse/Ponyville-Live#15]
The promotions for shows on the homepage are stuck on the ones from January 2018. Seems like something broke in the updating there.

**Comment by omnicons** [comment]
There haven't been any new posts added for it to read from since around January, so it appears that that is correct. We've got plans for the future of the site going forward that'll be announced in due time once we've got a few details worked out so stay tuned.

**Comment by Vaalyn** [comment]
> There haven't been any new posts added for it to read from since around January

@omnicons That's just plain wrong. I'm an admin for Brony Radio Germany and we have tried to promote not just one but multiple shows since January and none of them were shown.

**Comment by omnicons** [comment]
Oh, I'm referring from our tumblr that the API reads from.

**Comment by Vaalyn** [comment]
I'm referring to the promotion feature for shows from Google Calendar

**Comment by omnicons** [comment]
Can you contact me on Discord, I have some stuff to discuss with you. Aelwen#0001
