### ISSUE TITLE
Google Calendar XML Feeds not available anymore

### ISSUE THREAD

**Issue by Vaalyn** [Poniverse/Ponyville-Live#3]
Google has shut down their Calendar XML Feeds. The Station Profile Editor still wants a "Google Calendar XML Feed URL" but this URLs are not working anymore. The event schedule of a station can't be retrieved anymore.

**Comment by EventideGlow** [comment]
@Vaalyn Thanks for the report! I updated the instructions to point you to Google's iCal URL instead.

FYI: We only use the calendar URL to parse out the name of the calendar; the actual data is retrieved via the Google Calendar API, so XML URL's that have already been entered don't need to be updated.
